### ISSUE TITLE
Forwarding: template sets added twice if message contains both template definition and record

### ISSUE THREAD

**Issue by SecDorks-Kirc** [CESNET/ipfixcol#114]
The forwarding storage plugin adds template sets twice if a message contains both the template definition and an accompanying record. This is because the set is added by both `forwarding_remove_sent_templates` and `forwarding_update_templates` in `forwarding.c`.

**Comment by thorgrin** [comment]
Thanks for the report. I've looked into it and there was also a problem with UDP templates lifetime. I've just commited a fix. Please give it a try.
