### ISSUE TITLE
Issue with commit 50433958ad9b8417858abae166afae158a6be817

### ISSUE THREAD

**Issue by jrdalrymple** [CESNET/ipfixcol#115]
There was 1 file that was left broken I think:

plugins/input/nfdump/nfinput.c

316: -	for (i = 0; i < MSG_MAX_TEMPLATES; i++) {
316: +	for (i = 0; i < MSG_MAX_TEMPL_SETS; i++) {

Sorry - I would fix and issue a pull request but my system's git is tied to my personal github not my public one.

**Comment by SecDorks-Kirc** [comment]
This has already been fixed in the 'devel' branch some time ago. Please switch to that branch until a new release is made and code is synchronized to the 'master' branch.
