### ISSUE TITLE
fbitdump: IPv6 address prefix filter not working

### ISSUE THREAD

**Issue by DRiKE** [CESNET/ipfixcol#136]
Filtering on v6 prefixes does not work, and fbitdump returns all flows in the input files (i.e., no filtering is applied at all)

For example:
`fbitdump -R /my/fbitdata/ '%sa6 2001:db8::/32'`
will return flows that are not coming from 2001:db8

**Comment by thorgrin** [comment]
I've just fixed what i can in the fbitdump code. It should do the filtering now. However, the FastBit library does not support range queries on other values than floats (or doubles). Thus the addresses are converted to floating point numbers and the comparison is done after that. I may easily lead to incorrect results. I've sent a question about this to the FastBit mailing list an if they provide any means to do this properly, I'll update the fbitdump code.
