### ISSUE TITLE
Centralize non-IPFIX to IPFIX conversion code

### ISSUE THREAD

**Issue by SecDorks-Kirc** [CESNET/ipfixcol#137]
The code for converting non-IPFIX to IPFIX PDUs (`base/src/input/{sctp,tcp,udp}/convert.{c,h}` is currently duplicated among various input plugins. This is error-prone. Could we think about a way to centralize this code, perhaps under the 'util' umbrella?

**Comment by SecDorks-Kirc** [comment]
Same question for some external libraries that are used at multiple code occasions, such as *pugixml*.

**Comment by thorgrin** [comment]
Done for the conversion code in the latest commit. The pugixml is more complicated, more packages depend on the same code. It would have to be in a shared library, which I do not want to do for the third party code.
