### ISSUE TITLE
fbitdump: filtering on TCP flags

### ISSUE THREAD

**Issue by DRiKE** [CESNET/ipfixcol#143]
Filtering on TCP flags via `%flg`, for example `'%flg APS'`, yields no results.

After trying to fix this, it seems the following is happening (but I'm not sure how/where to fix it):
After parsing the string input, e.g. 'S' for flows containing a SYN packet, the resulting numerical value is parsed again. As the parser (`parseFlags()` in `DefaultPlugin.cpp`) expects flags in string format, it returns a numerical 0, resulting in no flows.
This is observed by simply adding some `printf()`'s in `parseFlag()` and printing the value of the `strFlags` argument:
```
printf("in parseFlags, input: %s\n", strFlags);
```

**Comment by thorgrin** [comment]
Thanks for spotting this, it should be fixed in the devel branch.

**Comment by DRiKE** [comment]
Thanks a lot for the fast fix, I'll try it right away.

**Comment by DRiKE** [comment]
Seems to work, only not as expected (coming from nfdump):
Using e.g. `%flg S` returns only S-only flows, instead of (what  I expected) flows including S-flags, so also `APS` etc.
I could not find anything in the man pages on the intended behaviour.

If you want me to open a separate ticket, let me know.

**Comment by thorgrin** [comment]
You are right, the behavior is a bit different. To support nfdump-like behavior we need to change quite a lot of things. Anyway, you can now do your query using: "%flg | 2 > 0". I'll look into it and add a support for parsing flags in such an expression so we will support queries like "%flg | S > 0". And we will mention that in the docs.

Is that enough for you or do you need the nfdump syntax to work as well?

**Comment by DRiKE** [comment]
I had no clue you could do that kind of stuff, neat! Although, I think in this case the correct filter would be based on a binary AND, i.e. `%flg & 2 > 0`, but I get the idea.

Anyway, thanks for clarifying, and for me personally, this is enough for the time being.

**Comment by thorgrin** [comment]
I've just fixed this so you can use "%flg & S > 0" or even "%flg & S = S".
