### ISSUE TITLE
IPFixcol

### ISSUE THREAD

**Issue by idsteiner** [CESNET/ipfixcol#156]
Hello, 

Would appreciate your help: whne i start ipfixcol there is the following message:
"INFO: configurator: _No profile configuration_"  - what this message means ?
I try to get the collector working for Cisco routers but it seems it does not work, no .ipfix file in tmp. The exporter works correctly on Cisco and i see tcpdump data hitting the UDP 2055 port. Please can you send me a simple startup.xml.  

Thanks
idsteiner

**Comment by thorgrin** [comment]
Hi,

the simplest configuration for UDP reception is the following:
```
<?xml version="1.0" encoding="UTF-8"?>
<ipfix xmlns="urn:ietf:params:xml:ns:yang:ietf-ipfix-psamp">

        <collectingProcess>
                <name>UDP collector</name>
                <udpCollector>
                        <name>Listening port 2055</name>
                        <localPort>2055</localPort>
                        <templateLifeTime>1800</templateLifeTime>
                        <optionsTemplateLifeTime>1800</optionsTemplateLifeTime>
                        <localIPAddress></localIPAddress>
                </udpCollector>
                <exportingProcess>IPFIXexport</exportingProcess>
        </collectingProcess>

        <!--## Exporting process configuration -->
        <exportingProcess>
                <name>IPFIXexport</name>
                <destination>
                        <name>Write to /tmp folder</name>
                        <fileWriter>
                                <fileFormat>ipfix</fileFormat>
                                <file>file://tmp/collected-records-tcp.ipfix</file>
                        </fileWriter>
                </destination>
        </exportingProcess>
</ipfix>
```

However, it might take several minutes for the data to appear, since you have to wait for the template to arrive. Which protocol does the router send? NetFlow v5, v9 or IPFIX?

The "INFO: configurator: No profile configuration" message is of no real consequence for you. The profiles can be used to sort the traffic and deal differently with specific flows. The message merely a notification that the profiles are not used.

Anyway, if this does not help, please send a complete output of the collector. If the collector connects, you should at least see it in the log.

Best regards,
Petr

**Comment by idsteiner** [comment]
thorgrin, 

thanks for your quick response. It seems it did not like LocalIPAddress=127.0.0.1 and after having changed it to the ip address of the interface (i have 2 interfaces on the srv), then it started to work. 

Now i have another question, would appreciate your answer : If the template and Data sets as follows, how can i do for ipfixcol to recognize the data inside so that ipfiview shows the data in a readbal format: do i need to write a code(plugin) or just modify some xml files (please can you specify what files). 

is there some more dicumentation about your product e.g. how to deal with domains, etc. 

Many thnaks again. 
 

--------------------------------------------------------------------------------
IPFIX Message Header:
	Version: 10
	Length: 236
	Export Time: 1454330791 (Mon Feb  1 07:46:31 2016)
	Sequence Number: 0
	Observation Domain ID: 0


Set Header:
	Set ID: 2 (Template Set)
	Length: 72
Template Record Header:
	Template ID: 256
	Field Count: 10
Fields:
	IE ID: 359		Field Length: 8
	IE ID: 6249		Field Length: 8 (PEN:4294967295)
	IE ID: 6250		Field Length: 8 (PEN:4294967295)
	IE ID: 6251		Field Length: 8 (PEN:4294967295)
	IE ID: 6252		Field Length: 8 (PEN:4294967295)
	IE ID: 4331		Field Length: 4 (PEN:4294967295)
	IE ID: 6232		Field Length: 4 (PEN:4294967295)
	IE ID: 14		Field Length: 4
	IE ID: 235		Field Length: 4
	IE ID: 83		Field Length: 8


Set Header:
	Set ID: 256 (Data Set)
	Length: 148
Data Record (#1):		(network byte order)
	IE ID: 359		Value: 0x794f9b52010000
	IE ID: 6249 (PEN:4294967295)	Value: 0x6fb46b35ec520100
	IE ID: 6250 (PEN:4294967295)	Value: 0xd400000000000000
	IE ID: 6251 (PEN:4294967295)	Value: 0xe803000000000000
	IE ID: 6252 (PEN:4294967295)	Value: 0xe000000000000000
	IE ID: 4331 (PEN:4294967295)	Value: 0
	IE ID: 6232 (PEN:4294967295)	Value: 0xe8030000
	IE ID: 14		Value: 0x2020202
	IE ID: 235		Value: 0x4040404
	IE ID: 83		Value: 0x8000000

**Comment by thorgrin** [comment]
Hi idsteiner,

The default configuration stores data in IPFIX file format, which is basically IPFIX messages written to file. If you look in plugins/storage directory of the repository, you'll see some other plugins for storing/sending data. I'd recommend you to try to get the [FastBit plugin](https://github.com/CESNET/ipfixcol/tree/master/plugins/storage/fastbit) working. It stores data locally and there is a query tool in [tools/fbitdump](https://github.com/CESNET/ipfixcol/tree/master/tools/fbitdump) which allows to print/sort/filter/aggregate the data. You'll need the FastBit library, we keep a clone here: https://github.com/CESNET/libfastbit

After you've installed the library, storage plugin and fbitdump tool, you just need to change the startup.xml to have destination for the fastbit plugin (man ipfixcol-fastbit-output). If some enterprise elements are not stored correctly, you might have to add their definition in /etc/ipfixcol/ipfix-elements.xml to let the collector know about them.

When you've successfully stored the data, the fbitdump tool can be used for queries (man fbitdump). You'll need to tell the fbitdump how to display the enterprise elements (just extend xml definition in /usr/share/fbitdump/fbitdump.xml). Then you can define your own output formats and perform queries.

**Comment by jepries** [comment]
@idsteiner I'm trying to interpret the exact same template you display above.  That PEN of 2^32-1 is driving me crazy.  Did you ever get definitions for that enterprise id=4294967295 and those ID's =6249, 6250, etc?

**Comment by thorgrin** [comment]
@idsteiner The thing with PEN 2^31-1 is that we use it to convert elements with IDs > 2^16. In NetFlow v9, you can have large IDs without any problem, but setting the first bit of EID to 1 in IPFIX means that the element also uses PEN. Thus we introduced the "all ones" PEN. In the NetFlow v9 data that your Cisco device is sending, the element 6249 is probably something like 2^16+6249. Does that make sense?

**Comment by jepries** [comment]
@thorgrin thanks for the hint.  So we know the incoming is v9, so I'm trying to figure out how to get the data interpreted.  The above shows up out of the json with 

"ipfix.e4294967295id6232": "250", 

If I interpret you right (we know this is cisco v9), we think they are sending us element id's in the 39000 range (not 65000+ range) based on their documentation here  http://docwiki.cisco.com/wiki/AVC-Export:PfR

so, since it is large and if we figure out the v9 to ipfix conversion all 1's PEN... we can maybe get this to work!  IT is obviously very consistent, we have the same problem @idsteiner has in interpreting the id's.

**Comment by jepries** [comment]
@thorgrin That's it!  39000 in binary, chop off the enterprise bit, you get 6232 left.  That's it, I think we can add mapping now to make the conversions!

**Comment by thorgrin** [comment]
@jepries Great! I'm glad that you can get this to work. I've discussed this in the IPFIX working group and there is no single opinion on how to do this. We are misusing the "all ones" PEN right now but thinking about proposing to dedicate an official one in the future. Until that time, we will be using the current approach.
