### ISSUE TITLE
Cannot get individual json files per ODID

### ISSUE THREAD

**Issue by jepries** [CESNET/ipfixcol#159]
ps: What i'm being told is there is 1 router exporting, but there are 6 ODID's incoming, not sure I believe it..., but could you validate my startup.xml please? I would like one IPFIX file to create along with a json file for each odid, not sure I'm doing it correctly.  It looks like i only get 1 json file per exporter, NOT per ODID.

I know I'm doing something wrong, but I've checked and rechecked and cannot figure this out.  Sorry to pester you so much.

I have this startup.xml below, I have 2 exporting processes, 1 for the ipfix file format and I want it to contain all ODID's, I have another exporter for JSON and I want a separate file for each ODID.

I don't get any ipfix file and only 1 json file, even though I see debug messages that indicate several json exporters were created and 1 ipfix exporter created.

Am I doing something stupid?

    <?xml version="1.0" encoding="UTF-8"?>
    <ipfix xmlns="urn:ietf:params:xml:ns:yang:ietf-ipfix-psamp">

        
        <collectingProcess>
                
                <name>UDP collector</name>
                
                <udpCollector>
                        
                        <name>Listening port 4739</name>
                        
                        <localPort>4739</localPort>
                        
                        <templateLifeTime>1800</templateLifeTime>
                        
                        <optionsTemplateLifeTime>1800</optionsTemplateLifeTime>
                        
                        
                        
                        
                        
                        <localIPAddress></localIPAddress>
                </udpCollector>
                
                <exportingProcess>File writer UDP</exportingProcess>
                <exportingProcess>JSON writer UDP</exportingProcess>
                
                <statisticsFile>/prod/eclapp/log/ipfixcol_stat.log</statisticsFile>
        </collectingProcess>

        
        <exportingProcess>
                
                <name>File writer UDP</name>
                 <singleManager>yes</singleManager>
                
                <destination>
                        <name>all ODIDs</name>
                        <fileWriter>
                                <fileFormat>ipfix</fileFormat>
                                <file>file://prod/test/flow/collected-records-udp-all-odid.ipfix</file>
                        </fileWriter>
                </destination>
        </exportingProcess>

        <exportingProcess>
          <name>JSON writer UDP</name>
          <destination>
              <name>ODID 9</name>
              <observationDomainId>9</observationDomainId>
              <fileWriter>
                 <fileFormat>json</fileFormat>
                 <metadata>no</metadata>
                 <tcpFlags>formated</tcpFlags>
                 <timestamp>epoc</timestamp>
                 <protocol>formated</protocol>
                 <ignoreUnknown>no</ignoreUnknown>
                 
                 
                 <output>
                   <type>file</type>
                   <path>/prod/test/flow/</path>
                   <prefix>json.9.</prefix>
                   <dumpInterval>
                     <timeWindow>300</timeWindow>
                     <timeAlignment>yes</timeAlignment>
                   </dumpInterval>
                 </output>
                 
               </fileWriter>
             </destination>
          <destination>
              <name>ODID 256</name>
              <observationDomainId>256</observationDomainId>
              <fileWriter>
                 <fileFormat>json</fileFormat>
                 <metadata>no</metadata>
                 <tcpFlags>formated</tcpFlags>
                 <timestamp>epoc</timestamp>
                 <protocol>formated</protocol>
                 <ignoreUnknown>no</ignoreUnknown>
                 
                 
                 <output>
                   <type>file</type>
                   <path>/prod/test/flow/</path>
                   <prefix>json.256.</prefix>
                   <dumpInterval>
                     <timeWindow>300</timeWindow>
                     <timeAlignment>yes</timeAlignment>
                   </dumpInterval>
                 </output>
                 
               </fileWriter>
             </destination>
          <destination>
              <name>ODID 259</name>
              <observationDomainId>259</observationDomainId>
              <fileWriter>
                 <fileFormat>json</fileFormat>
                 <metadata>no</metadata>
                 <tcpFlags>formated</tcpFlags>
                 <timestamp>epoc</timestamp>
                 <protocol>formated</protocol>
                 <ignoreUnknown>no</ignoreUnknown>
                 
                 
                 <output>
                   <type>file</type>
                   <path>/prod/test/flow/</path>
                   <prefix>json.259.</prefix>
                   <dumpInterval>
                     <timeWindow>300</timeWindow>
                     <timeAlignment>yes</timeAlignment>
                   </dumpInterval>
                 </output>
                 
               </fileWriter>
             </destination>
          <destination>
              <name>ODID 261</name>
              <observationDomainId>261</observationDomainId>
              <fileWriter>
                 <fileFormat>json</fileFormat>
                 <metadata>no</metadata>
                 <tcpFlags>formated</tcpFlags>
                 <timestamp>epoc</timestamp>
                 <protocol>formated</protocol>
                 <ignoreUnknown>no</ignoreUnknown>
                 
                 
                 <output>
                   <type>file</type>
                   <path>/prod/test/flow/</path>
                   <prefix>json.261.</prefix>
                   <dumpInterval>
                     <timeWindow>300</timeWindow>
                     <timeAlignment>yes</timeAlignment>
                   </dumpInterval>
                 </output>
                 
               </fileWriter>
             </destination>
          <destination>
              <name>ODID 65797</name>
              <observationDomainId>65797</observationDomainId>
              <fileWriter>
                 <fileFormat>json</fileFormat>
                 <metadata>no</metadata>
                 <tcpFlags>formated</tcpFlags>
                 <timestamp>epoc</timestamp>
                 <protocol>formated</protocol>
                 <ignoreUnknown>no</ignoreUnknown>
                 
                 
                 <output>
                   <type>file</type>
                   <path>/prod/test/flow/</path>
                   <prefix>json.65797.</prefix>
                   <dumpInterval>
                     <timeWindow>300</timeWindow>
                     <timeAlignment>yes</timeAlignment>
                   </dumpInterval>
                 </output>
                 
               </fileWriter>
             </destination>
             <destination>
              <name>ODID 65795</name>
              <observationDomainId>65795</observationDomainId>
              <fileWriter>
                 <fileFormat>json</fileFormat>
                 <metadata>no</metadata>
                 <tcpFlags>formated</tcpFlags>
                 <timestamp>epoc</timestamp>
                 <protocol>formated</protocol>
                 <ignoreUnknown>no</ignoreUnknown>
                 
                 
                 <output>
                   <type>file</type>
                   <path>/prod/test/flow/</path>
                   <prefix>json.67595.</prefix>
                   <dumpInterval>
                     <timeWindow>300</timeWindow>
                     <timeAlignment>yes</timeAlignment>
                   </dumpInterval>
                 </output>
                 
               </fileWriter>
             </destination>
             <destination>
              <name>UNKNOWN ODID</name>
              <fileWriter>
                 <fileFormat>json</fileFormat>
                 <metadata>no</metadata>
                 <tcpFlags>formated</tcpFlags>
                 <timestamp>epoc</timestamp>
                 <protocol>formated</protocol>
                 <ignoreUnknown>no</ignoreUnknown>
                 
                 
                 <output>
                   <type>file</type>
                   <path>/prod/test/flow/</path>
                   <prefix>json.unknown.</prefix>
                   <dumpInterval>
                     <timeWindow>300</timeWindow>
                     <timeAlignment>yes</timeAlignment>
                   </dumpInterval>
                 </output>
                 
               </fileWriter>
             </destination>
        </exportingProcess>

        
        <intermediatePlugins>
                
                <dummy_ip>
                </dummy_ip>

        </intermediatePlugins>
    </ipfix>

Here is debug (./configure --enable-debug) and -v3 output that shows I've actually created multiple json storage....

    INFO: dummy Intermediate Process: Successfully initialized
    INFO: configurator: [26698] Opening storage xml_conf: /usr/share/ipfixcol/plugins/ipfixcol-json-output.so
    INFO: configurator: [26698] Opening storage xml_conf: /usr/share/ipfixcol/plugins/ipfixcol-json-output.so
    INFO: configurator: [26698] Opening storage xml_conf: /usr/share/ipfixcol/plugins/ipfixcol-json-output.so
    INFO: configurator: [26698] Opening storage xml_conf: /usr/share/ipfixcol/plugins/ipfixcol-json-output.so
    INFO: configurator: [26698] Opening storage xml_conf: /usr/share/ipfixcol/plugins/ipfixcol-json-output.so
    INFO: configurator: [26698] Opening storage xml_conf: /usr/share/ipfixcol/plugins/ipfixcol-json-output.so
    INFO: configurator: [26698] Opening storage xml_conf: /usr/share/ipfixcol/plugins/ipfixcol-json-output.so
    INFO: configurator: [26698] Opening storage xml_conf: /usr/share/ipfixcol/plugins/ipfixcol-ipfix-output.so

One thing I notice is that I only see 1 of these records:

    ...
    INFO: UDP input: New UDP exporter connected (unique port and address)
    DEBUG: ipfix_message: [259] Processing data
    DEBUG: json_storage: initialized
    INFO: output manager: [259] Data Manager created
    DEBUG: output manager: [259] New source
    DEBUG: json_storage(file): Thread started...
    DEBUG: ipfix_message: [259] Processing data
    ....

I don't see a "New UDP exporter for any of the other ODID's I'm expecting, but I do see records being processed for them:

    ....
    DEBUG: ipfix_message: [261] Processing data
    WARNING: preprocessor: [261] Data template with ID 256 not found
    <NOTE: that warning goes away when I get the template>
    DEBUG: dummy Intermediate Process: got IPFIX message!
    ....

So it looks like I have 1 exporter incoming with multiple ODID's (9, 256, 259, 261, 65797....)

A single router can have multiple ODID's as I understand it, different processes can have their own?  I'm confused as to what I'm seeing.  No IPFIX file and only one JSON file

    [test@VH-BLT0 flow]$ pwd
    /prod/test/flow
    [test@VH-BLT0 flow]$ ls -lt
    total 7604
    -rw-rw-r--. 1 test test 1019026 Feb 29 17:57 json.259.201602292255
    -rw-rw-r--. 1 test test 2171132 Feb 29 17:55 json.259.201602292250
    -rw-rw-r--. 1 test test 2031868 Feb 29 17:50 json.259.201602292245
    -rw-rw-r--. 1 test test 2129968 Feb 29 17:45 json.259.201602292240
    -rw-rw-r--. 1 test test  418509 Feb 29 17:40 json.259.201602292235

**Comment by thorgrin** [comment]
Currently only one exportingProcess is supported. There are two ways to get multiple plugins process the same data: multiple exporting processes and multiple destinations. Therefore, for simplicity, we decided to drop support for multiple exporting processes and just support multiple destinations. However, you must decide whether to use singleManager or not, you cannot have it only for some destinations.

Please try multiple json files using only one exportingProcess and see whether that works.

**Comment by jepries** [comment]
Will do. One thing about above config that I'll verify today, it seemed like I got one destination per exporter not one destination per odid. One exporter has multiple odids, only the first one discovered created a json file, I'll verify with the ipfix exporting process removed.

**Comment by jepries** [comment]
Confirmed, I have 1 exporter with multiple ODID's.  Only the first ODID seen gets a file, the rest do not get an ODID.  The rule is really 1 file per exporter, not per ODID.  It's ok though, I found that odip plugin last night in the codebase that is really what I wanted in the first place, now I know what router the record was exported from, that's all I really wanted.

Here is the (comments removed) startup.xml I was running, only got 1 json output file:

    <?xml version="1.0" encoding="UTF-8"?>
    <ipfix xmlns="urn:ietf:params:xml:ns:yang:ietf-ipfix-psamp">
        <collectingProcess>
                <name>UDP collector</name>
                <udpCollector>
                        <name>Listening port 4739</name>
                        <localPort>4739</localPort>
                        <templateLifeTime>1800</templateLifeTime>
                        <optionsTemplateLifeTime>1800</optionsTemplateLifeTime>
                        <localIPAddress></localIPAddress>
                </udpCollector>
                <exportingProcess>JSON writer UDP</exportingProcess>
                <statisticsFile>/prod/eclapp/log/ipfixcol_stat.log</statisticsFile>
        </collectingProcess>

        <exportingProcess>
          <name>JSON writer UDP</name>
          <destination>
              <name>ODID 9</name>
              <observationDomainId>9</observationDomainId>
              <fileWriter>
                 <fileFormat>json</fileFormat>
                 <metadata>no</metadata>
                 <tcpFlags>formated</tcpFlags>
                 <timestamp>epoc</timestamp>
                 <protocol>formated</protocol>
                 <ignoreUnknown>no</ignoreUnknown>
                 <output>
                   <type>file</type>
                   <path>/prod/test/flow/</path>
                   <prefix>json.9.</prefix>
                   <dumpInterval>
                     <timeWindow>300</timeWindow>
                     <timeAlignment>yes</timeAlignment>
                   </dumpInterval>
                 </output>
               </fileWriter>
             </destination>
          <destination>
              <name>ODID 256</name>
              <observationDomainId>256</observationDomainId>
              <fileWriter>
                 <fileFormat>json</fileFormat>
                 <metadata>no</metadata>
                 <tcpFlags>formated</tcpFlags>
                 <timestamp>epoc</timestamp>
                 <protocol>formated</protocol>
                 <ignoreUnknown>no</ignoreUnknown>
                 <output>
                   <type>file</type>
                   <path>/prod/test/flow/</path>
                   <prefix>json.256.</prefix>
                   <dumpInterval>
                     <timeWindow>300</timeWindow>
                     <timeAlignment>yes</timeAlignment>
                   </dumpInterval>
                 </output>
               </fileWriter>
             </destination>
          <destination>
              <name>ODID 259</name>
              <observationDomainId>259</observationDomainId>
              <fileWriter>
                 <fileFormat>json</fileFormat>
                 <metadata>no</metadata>
                 <tcpFlags>formated</tcpFlags>
                 <timestamp>epoc</timestamp>
                 <protocol>formated</protocol>
                 <ignoreUnknown>no</ignoreUnknown>
                 <output>
                   <type>file</type>
                   <path>/prod/test/flow/</path>
                   <prefix>json.259.</prefix>
                   <dumpInterval>
                     <timeWindow>300</timeWindow>
                     <timeAlignment>yes</timeAlignment>
                   </dumpInterval>
                 </output>
               </fileWriter>
             </destination>
          <destination>
              <name>ODID 261</name>
              <observationDomainId>261</observationDomainId>
              <fileWriter>
                 <fileFormat>json</fileFormat>
                 <metadata>no</metadata>
                 <tcpFlags>formated</tcpFlags>
                 <timestamp>epoc</timestamp>
                 <protocol>formated</protocol>
                 <ignoreUnknown>no</ignoreUnknown>
                 <output>
                   <type>file</type>
                   <path>/prod/test/flow/</path>
                   <prefix>json.261.</prefix>
                   <dumpInterval>
                     <timeWindow>300</timeWindow>
                     <timeAlignment>yes</timeAlignment>
                   </dumpInterval>
                 </output>
               </fileWriter>
             </destination>
          <destination>
              <name>ODID 65797</name>
              <observationDomainId>65797</observationDomainId>
              <fileWriter>
                 <fileFormat>json</fileFormat>
                 <metadata>no</metadata>
                 <tcpFlags>formated</tcpFlags>
                 <timestamp>epoc</timestamp>
                 <protocol>formated</protocol>
                 <ignoreUnknown>no</ignoreUnknown>
                 <output>
                   <type>file</type>
                   <path>/prod/test/flow/</path>
                   <prefix>json.65797.</prefix>
                   <dumpInterval>
                     <timeWindow>300</timeWindow>
                     <timeAlignment>yes</timeAlignment>
                   </dumpInterval>
                 </output>
               </fileWriter>
             </destination>
             <destination>
              <name>ODID 65795</name>
              <observationDomainId>65795</observationDomainId>
              <fileWriter>
                 <fileFormat>json</fileFormat>
                 <metadata>no</metadata>
                 <tcpFlags>formated</tcpFlags>
                 <timestamp>epoc</timestamp>
                 <protocol>formated</protocol>
                 <ignoreUnknown>no</ignoreUnknown>
                 <output>
                   <type>file</type>
                   <path>/prod/test/flow/</path>
                   <prefix>json.67595.</prefix>
                   <dumpInterval>
                     <timeWindow>300</timeWindow>
                     <timeAlignment>yes</timeAlignment>
                   </dumpInterval>
                 </output>
               </fileWriter>
             </destination>
             <destination>
              <name>UNKNOWN ODID</name>
              <fileWriter>
                 <fileFormat>json</fileFormat>
                 <metadata>no</metadata>
                 <tcpFlags>formated</tcpFlags>
                 <timestamp>epoc</timestamp>
                 <protocol>formated</protocol>
                 <ignoreUnknown>no</ignoreUnknown>
                 <output>
                   <type>file</type>
                   <path>/prod/test/flow/</path>
                   <prefix>json.unknown.</prefix>
                   <dumpInterval>
                     <timeWindow>300</timeWindow>
                     <timeAlignment>yes</timeAlignment>
                   </dumpInterval>
                 </output>
               </fileWriter>
             </destination>
        </exportingProcess>


        <intermediatePlugins>
                <dummy_ip>
                </dummy_ip>
        </intermediatePlugins>
    </ipfix>

**Comment by thorgrin** [comment]
I'm glad that you found a solution. I'll look into this to see why your configuration does not work as expected. However, we plan to drop this ODID specific configuration in the future and let the output plugins handle multiple ODIDs.

**Comment by thorgrin** [comment]
OK, I've verified that multiple exporters with multiple ODIDs get their own files. However, the collector expects only one ODID per source at this point. We realize that this is not necessarily true and will work to lift this limitation in the future. Until then,  I'll close this issue.
