### ISSUE TITLE
fbitdump does not build with libfastbit (May 16, 2016)

### ISSUE THREAD

**Issue by SecDorks-Kirc** [CESNET/ipfixcol#172]
Since the update of _libfastbit_ on May 16, 2016, _fbitdump_ does not build anymore:

```
g++ -DHAVE_CONFIG_H -I. -I..  -I../3rdparty  -Wall -O2 -std=gnu++11 -fno-strict-aliasing  -MT AggregateFilter.o -MD -MP -MF .deps/AggregateFilter.Tpo -c -o AggregateFilter.o AggregateFilter.cpp
In file included from Column.h:45:0,
                 from Configuration.h:45,
                 from Filter.h:44,
                 from AggregateFilter.h:44,
                 from AggregateFilter.cpp:40:
Cursor.h:98:2: error: 'typeList' in 'class ibis::table' does not name a type
  ibis::table::typeList columnTypes; /**< Column types of the table */
  ^
```

**Comment by thorgrin** [comment]
Thanks for reporting that, I've just fixed fbitdump and fastbit output plugin. Both require the latest libfastbit version to build now.

One drawback is that compilation with fastbit-compression library is not possible anymore. However, this option was not used and the library with compression support was not maintained any longer.
