### ISSUE TITLE
fbitdump: expansion of time specifications broken

### ISSUE THREAD

**Issue by SecDorks-Kirc** [CESNET/ipfixcol#175]
According to _fbitdump_'s man page, 
> any parts of the time spec may be omitted e.g YYYY/MM/dd expands to YYYY/MM/dd.00:00:00-infinity and processes all flow from a given day onwards

However, when specifying an abbreviated timestamp like `2016/07/12.05:35`, _fbitdump_ reports the following error:

`Warning -- ibis::whereParser encountered syntax error, unexpected floating-point number, expecting name string or string literal at location...`

**Comment by thorgrin** [comment]
The documentation seems to be simply wrong, the code currently does not support this at all. Unless you need this feature, I'll update the man page and remove the erroneous information.

**Comment by SecDorks-Kirc** [comment]
We don't really need this functionality right now, so removing it from the documentation seems to be enough.
