### ISSUE TITLE
Duplicate data written to fields when a field is blank

### ISSUE THREAD

**Issue by sdavieshpe** [CESNET/ipfixcol#186]
I have been using IPFIXcol very successfully but have been having a strange issue where if an blank entry is sent it gets written to the JSON file and repeated in the next few elements see below. id 204 has 0x3b but it gets repeated in the following elements instead of the data it should be. This is on the latest dev branch code.

"ipfix.e1XXXXid204": "0x3b", "ipfix.e1XXXXid210": "0x3b", "ipfix.e1XXXXid211": "0x3b",

Cheers
S.

**Comment by thorgrin** [comment]
I've just pushed a commit that should fix this problem (branch  issue-#186) . Could you please give it a try and let us know if it works? I do not have the dataset to test this myself right now. Thanks.

**Comment by sdavieshpe** [comment]
Thanks thorgrin

Will get a test underway as soon as I can and provide feedback. Thanks for the fast turnaround :)

S.

**Comment by sdavieshpe** [comment]
Testing shows that the issue has been fixed.
