### ISSUE TITLE
ipfixcol cannot pass build.

### ISSUE THREAD

**Issue by zhexiao** [CESNET/ipfixcol#190]
Dears, 

I try to build ipfixcol on my PC, but looks like i have some problems with the packages or plugins.
It's show me a configure error:
```shell
...
checking for /etc/protocols... yes
checking for library containing siso_create... no
configure: error: Required library siso missing
```

My OS is ubuntu 16.04.

Best
Zhe

**Comment by thorgrin** [comment]
Could you provide more information? Do you build from the root or just the base? If from root, which plugin fails?

Thanks

**Comment by zhexiao** [comment]
Dear,

I try to build ipfixcol json stroage, this following code is what i did in the command:

```shell
> wget https://github.com/CESNET/ipfixcol/archive/devel.zip
> cd ipfixcol-devel/plugins/storage/json/
> sudo autoreconf -i 
> sudo ./configure --with-distro=debian
```

After  **sudo ./configure --with-distro=debian**, the error displayed:

checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
configure: Using username "" and email ""
checking for rpmbuild... no
checking for xsltproc... xsltproc
checking whether make sets $(MAKE)... (cached) yes
checking for gawk... (cached) gawk
checking whether CC supports -std=gnu++11... yes
checking for /etc/protocols... yes
checking for library containing siso_create... no
configure: error: Required library siso missing

**Comment by zhexiao** [comment]
Dears, 

Never mind, i find i need to build ipfixcol first, then build json storage. Now i passed the build.

I am sorry for that.

Thanks

**Comment by thorgrin** [comment]
Well, you seem to be trying to build the plugin without the collector itself installed. Please install the IPFIXcol base first:
```
cd ipfixcol-devel/
autoreconf -i
./configure
make
sudo make install
```
and then try the json plugin. Please not that the sudo is required only for installation, so you can (and should) run autoreconf and ./configure without it.

**Comment by thorgrin** [comment]
I seems that we have posted at the same time ;-) No worries, I hope it works well for you.

**Comment by zhexiao** [comment]
Thanks . Yaha
