### ISSUE TITLE
observationDomainName 

### ISSUE THREAD

**Issue by TTpartizan** [CESNET/ipfixcol#197]
hi
recognizes observationDomainName  id 300  IPFIX ?

need domain name collect

**Comment by thorgrin** [comment]
I've updated ipfix-elements.xml file to contain new elements straight from http://www.iana.org/assignments/ipfix/ipfix.xhtml (devel branch)

The collector supports it, but you need to make sure that the storage plugin supports it as well (depends on what you are using)
