### ISSUE TITLE
Differentiate Netflow Records from different sources

### ISSUE THREAD

**Issue by zhaoyea** [CESNET/ipfixcol#201]
Hi, I know that a netflow collector can be the collector for many devices. Can IPFixcol differentiate the records. For eg. If server1-> ipfixcol(PORT:6003), server2->ipfixcol(PORT:6003), server3->ipfixcol(PORT:6003) scenario is like this, how can I identify the netflow data that is coming from server 1 or 2 or 3 and save them according to where they come from. What are the changes needed in the startup.xml file.
Thanks!

**Comment by thorgrin** [comment]
Hello, it depends on what storage/output plugin is used. Each plugin has information about source available, but they might be using it differently or discarding it completely. For example, the fastbit storage plugin can use observation domain id (ODID) and IP address to store data from different sources in different directories. On the other hand, the json plugin disregards this information entirely.

If you want to have exporter source IP address available for each flow record, you can use the odip intermediate plugin - just add <odip_ip/> to the intermediate plugins section in the startup.xml.

**Comment by zhaoyea** [comment]
Thanks for the clarification !! 
Based on your explanation, by using the odip_ip with the fastbit storage. My startup.xml should turn out like this right?

<?xml version="1.0" encoding="UTF-8"?>
<ipfix xmlns="urn:ietf:params:xml:ns:yang:ietf-ipfix-psamp">

        <collectingProcess>
                .
                .
                .				
        </collectingProcess>

       <intermediatePlugin>
		<name>odip</name>
		<odip_ip>(ip_addr_of_exportor)</odip_ip>
		<threadName>odip_inter</threadName>
       </intermediatePlugin>

        
        <exportingProcess>
                <name>fastbit</name>
		<destination>
			<name>store data records in FastBit database</name>
			 <fileWriter>
				  <fileFormat>fastbit</fileFormat>
				  <path>/tmp/ipfixcol/flow/%o/%Y/%m/%d/</path>
				  <dumpInterval>
					   <timeWindow>300</timeWindow>
					   <timeAlignment>yes</timeAlignment>
					   <recordLimit>no</recordLimit>
					   <bufferSize>50000</bufferSize>
				  </dumpInterval>
				  <namingStrategy>
					   <type>time</type>
					   <prefix>ic</prefix>
				  </namingStrategy>
				  <onTheFlyIndexes>yes</onTheFlyIndexes>
				  <reorder>no</reorder>
				  <indexes>
					   <element enterprise = "0" id = "12"/>
					   <element enterprise = "0" id = "8"/>
					   <element id = "4"/>
				  </indexes>
			 </fileWriter>
		 </destination>
        </exportingProcess>
</ipfix>

**Comment by thorgrin** [comment]
If you are using the FastBit storage, than you can use:
<path>/tmp/ipfixcol/flow/%E/%Y/%m/%d/</path>
To incorporate source exporter IP address in the path. If you provided each exporter with unique ODID, it would have separated them already in the current setting. 

That said, if you want to use the odip plugin, just add
```
        <intermediatePlugins>
                <odip_ip/>
        </intermediatePlugins>
```
after the </exportingProcess>

**Comment by zhaoyea** [comment]
Thanks for the clear explanation ! I manage to do it with fastbit. Just out of curiosity, other than fastbit, what other storage plugin is able to perform the intended output (identify source exporter IP address). 

Thank you !

**Comment by thorgrin** [comment]
I'm glad to help. I think that only the fastbit can do that currently. We did not need it for other plugins, yet. If you have a usecase where this is useful, please create a new issue with a proposal for the feature and we will consider extending the appropriate plugin. Thanks!
