### ISSUE TITLE
How to add ODID as an additional field in json output

### ISSUE THREAD

**Issue by vi9dgupta** [CESNET/ipfixcol#203]
It would be of great help if ODID is also written along with flows in json output.

**Comment by thorgrin** [comment]
This would require passing a pointer to the ipfix_msg->input_info structure to Storage::storeDataRecord method (https://github.com/CESNET/ipfixcol/blob/master/plugins/storage/json/Storage.cpp#L105), adding a configuration option for this feature and updating the Storage::storeDataRecord to add input_info->odid to the json message.

Optionally, we can add option for including source IP address and source port as well.

It seems quite easy, you can do it yourself and make a pull request or wait a bit till I find some time to implement it.

**Comment by thorgrin** [comment]
I've just commited the code to the devel branch.  Just by adding `<odid>yes</odid>` to the configuration, you should be able to print the odid. Please let me know if there is a problem with the code, I've tested it only on a small sample. Thanks
