### ISSUE TITLE
IPFIX Exporter IP in JSON output

### ISSUE THREAD

**Issue by vi9dgupta** [CESNET/ipfixcol#214]
How can we print an Exporter IP to JSON output ?

**Comment by Lukas955** [comment]
Hi,
this feature is available in JSON plugin for the new [IPFIXcol2](https://github.com/CESNET/ipfixcol2).

See description of the new plugin [here](https://github.com/CESNET/ipfixcol2/tree/master/src/plugins/output/json) -> `detailedInfo` parameter.

**Comment by vi9dgupta** [comment]
We knew that. But actually Kafka Plugin is not still available there.

**Comment by Lukas955** [comment]
If everything goes well, there will be support for Kafka by the end of the next week.

**Comment by Lukas955** [comment]
Hi, I run into some issues with loading librdkafka during collector startup - I reported the issue to authors of the library (https://github.com/edenhill/librdkafka/issues/2681) and managed to find workaround. However, it took me some time and i will have short delay.

**Comment by Lukas955** [comment]
Hi, I run into some issues with loading librdkafka during collector startup - I reported the issue to authors of the library and managed to find workaround. However, it took me some time and i will have short delay.

**Comment by Lukas955** [comment]
The new JSON plugin (for IPFIXcol2) now supports Kafka (devel branch).
