### ISSUE TITLE
Announced file "sample.cpp" missing

### ISSUE THREAD

**Issue by bortzmeyer** [CESNET/ipfixcol#216]
https://github.com/CESNET/ipfixcol/tree/master/base/src/intermediate/anonymization/Crypto-PAn says "sample.cpp	This is a sample program to illustrate the use of class 
		PAnonymizer."

But I do not find sample.cpp in the Github repository.

**Comment by Lukas955** [comment]
Hi,

this is not repository of Crypto-PAn.

This code is part of an anonymization module of the collector and I assume that some source files were just adjusted/remove to meet needs of the module.
