### ISSUE TITLE
fbitdump voip_rtpcode-plugin: unreachable code fragment

### ISSUE THREAD

**Issue by SecDorks-Kirc** [CESNET/ipfixcol#27]
In `voip_rtpcodec.c`, there is a code fragment that can never be reached. It is the call to `snprintf` on line 134. Perhaps, one of the conditions that come just before line 134 shouldn't feature a `return` statement. In case they do, line 134 can be removed completely.

**Comment by mikeek** [comment]
Fixed in 836f591ce7ba10b19e61b3ad3a103b55d64d255a
