### ISSUE TITLE
Unirec storage plugin: libtrap not available for Debian/Ubuntu

### ISSUE THREAD

**Issue by SecDorks-Kirc** [CESNET/ipfixcol#81]
The `libtrap` library, which is required for the Unirec storage plugin, is not available on Debian/Ubuntu-based systems. As such, building IPFIXcol from the top-level directory always fails. I therefore propose to not build the Unirec plugin if 1) compiled from the top-level directory and 2) Debian/Ubuntu is detected. Do you agree, or do you propose another solution?

**Comment by thorgrin** [comment]
I agree with the first option, since it is not part of any other distro either. FYI, it can be downloaded here: https://www.liberouter.org/technologies/nemea/
