### ISSUE TITLE
autoreconf fails on CentOS 5

### ISSUE THREAD

**Issue by SecDorks-Kirc** [CESNET/ipfixcol#90]
Building IPFIXcol on CentOS 5 fails with the following errors:

```
[root@localhost base]# autoreconf -if
aclocal:configure.ac:132: warning: macro 'AM_COND_IF' not found in library
aclocal:configure.ac:150: warning: macro 'AM_COND_IF' not found in library
aclocal:configure.ac:216: warning: macro 'AM_COND_IF' not found in library
aclocal:configure.ac:221: warning: macro 'AM_COND_IF' not found in library
configure.ac:39: error: Autoconf version 2.60 or higher is required
configure.ac:39: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
aclocal: autom4te failed with exit status: 63
autoreconf: aclocal failed with exit status: 63
[root@localhost base]# autoreconf --version
autoreconf (GNU Autoconf) 2.59
<snip>
[root@localhost base]# aclocal --version
aclocal (GNU automake) 1.9.6
<snip>
[root@localhost base]#
```

Similar errors, although for a different macro and without referred to `Autoconf version 2.60`, occur when trying to build CESNET's libfast fork. 

Even though a potential solution to the problem is provided in the error messages (i.e., installing a more recent version of Autoconf), it is sometimes far from straightforward to accomplish this. This can be the case due to dependency issues, for example. My questions now are twofold:

1. Is the requirement for Autoreconf 2.60 (or perhaps v2.68) very hard, or would it be possible to have different code paths depending on the version of Autoreconf available on the system?
2. Do you have any experience with building IPFIXcol (and libfastbit) on CentOS 5 systems?
3. Any other suggestions on how to solve this problem?

**Comment by thorgrin** [comment]
Although it might be possible to make the autoconf/automake system work with some effort, the CentOS 5 system has old version of c++ compiler which does not support all the c++11 features used by some IPFIXcol components. We recommned to use [devtoolset2](http://linux.web.cern.ch/linux/devtoolset/#install) to install more recent build system on the CentOS 5. You will also have to manually update xsl-stylesheets in /usr/share/sgml/docbook/xsl-stylesheets, preferrably by changing the symlink to some newer version. After that, you should be able to install the ipfixcol software and even create rpm packages on the CentOS 5 system.
